# Explotary Data Analysis for New Egg Products

In [ ]:
# Load dataset and view basic structure
import pandas as pd
import numpy as np

pd.set_option("display.max_rows", None)
pd.set_option("display.max_seq_items", None)

df=pd.read_csv("filtered_products_newegg.csv")

## Check structure and dimensions

In [59]:
#shape
df.shape

(2605, 10)

In [60]:
# Check structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2605 entries, 0 to 2604
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   itemNumber             2605 non-null   object
 1   class                  2605 non-null   object
 2   name                   2603 non-null   object
 3   customerReviewAverage  2605 non-null   float64
 4   customerReviewCount    2605 non-null   int64
 5   customerTopRated       2605 non-null   bool
 6   modelNumber            2602 non-null   object
 7   salePrice              2605 non-null   float64
 8   manufacturer           2605 non-null   object
 9   isRefurbished          2605 non-null   bool
dtypes: bool(2), float64(2), int64(1), object(5)
memory usage: 168.0+ KB

In [61]:
# Missing values summary
df.isnull().sum()

itemNumber               0
class                    0
name                     2
customerReviewAverage    0
customerReviewCount      0
customerTopRated         0
modelNumber              3
salePrice                0
manufacturer             0
isRefurbished            0
dtype: int64

In [62]:
# Print the number of rows and columns
print(f"The number of rows= {df.shape[0]}")
print(f"The number of columns= {df.shape[1]}")

The number of rows= 2605
The number of columns= 10

## Columns and Data Types

In [63]:
#display the columns
df.columns

Index(['itemNumber', 'class', 'name', 'customerReviewAverage',
       'customerReviewCount', 'customerTopRated', 'modelNumber', 'salePrice',
       'manufacturer', 'isRefurbished'],
      dtype='object')

In [64]:
df.columns.to_list()

['itemNumber',
 'class',
 'name',
 'customerReviewAverage',
 'customerReviewCount',
 'customerTopRated',
 'modelNumber',
 'salePrice',
 'manufacturer',
 'isRefurbished']

In [65]:
# Data Types
df.dtypes

itemNumber                object
class                     object
name                      object
customerReviewAverage    float64
customerReviewCount        int64
customerTopRated            bool
modelNumber               object
salePrice                float64
manufacturer              object
isRefurbished               bool
dtype: object

## Clean Data

In [66]:
#remove rows that are empty
df = df.dropna()

In [67]:
# Drop duplicates if any
df.drop_duplicates(inplace=True)

/var/folders/tr/q_np2b5j1hnczlwdkh_7fpd00000gn/T/ipykernel_43735/1556042700.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [68]:
df.isnull().sum()

itemNumber               0
class                    0
name                     0
customerReviewAverage    0
customerReviewCount      0
customerTopRated         0
modelNumber              0
salePrice                0
manufacturer             0
isRefurbished            0
dtype: int64

In [69]:
df = df[df['customerReviewCount'] != 0]

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 618 entries, 0 to 2587
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   itemNumber             618 non-null    object
 1   class                  618 non-null    object
 2   name                   618 non-null    object
 3   customerReviewAverage  618 non-null    float64
 4   customerReviewCount    618 non-null    int64
 5   customerTopRated       618 non-null    bool
 6   modelNumber            618 non-null    object
 7   salePrice              618 non-null    float64
 8   manufacturer           618 non-null    object
 9   isRefurbished          618 non-null    bool
dtypes: bool(2), float64(2), int64(1), object(5)
memory usage: 44.7+ KB

## Descriptive Statistics

In [71]:
# Summary statistics for numeric columns
df.describe()
df.describe(percentiles=[.1, .25, .5, .75, .9])

       customerReviewAverage  customerReviewCount    salePrice
count             618.000000           618.000000   618.000000
mean                4.214725            31.804207   954.188091
std                 1.031871            93.610588   883.862430
min                 1.000000             1.000000    79.000000
10%                 3.000000             1.000000   178.466000
25%                 4.000000             1.000000   318.240000
50%                 4.500000             3.000000   671.000000
75%                 5.000000            20.750000  1379.990000
90%                 5.000000            71.000000  1999.990000
max                 5.000000           892.000000  7499.000000

In [72]:
# Summary statistics for categorical columns
df.describe(include='object')

,itemNumber,class,name,modelNumber,manufacturer
count,618,618,618,618,618
unique,618,3,615,607,70
top,83-360-831,desktop,HP EliteDesk 800 G9 Mini Desktop Intel Core i7...,FX608JHR-ES73,DELL
freq,1,423,2,4,92

In [73]:
# Univariate Analysis — Numerical
print('Review count Summary:\n ', df['customerReviewCount'].describe())
print('\nReview avg Score Summary:\n ', df['customerReviewAverage'].describe())
print('\n Sale Price Summary:\n ', df['salePrice'].describe())

# Univariate Analysis — Categorical
print('\nManufacturer Summary:\n ', df['manufacturer'].describe())
print('\nclass Summary:\n ', df['class'].describe())
print('\nModel number Summary:\n ', df['modelNumber'].describe())
print('\ncondition Summary:\n ', df['isRefurbished'].describe())
print('\nManufacturer num:\n ', df['manufacturer'].value_counts())
print('\nclass num:\n ', df['class'].value_counts())

Review count Summary:
  count    618.000000
mean      31.804207
std       93.610588
min        1.000000
25%        1.000000
50%        3.000000
75%       20.750000
max      892.000000
Name: customerReviewCount, dtype: float64

Review avg Score Summary:
  count    618.000000
mean       4.214725
std        1.031871
min        1.000000
25%        4.000000
50%        4.500000
75%        5.000000
max        5.000000
Name: customerReviewAverage, dtype: float64

 Sale Price Summary:
  count     618.000000
mean      954.188091
std       883.862430
min        79.000000
25%       318.240000
50%       671.000000
75%      1379.990000
max      7499.000000
Name: salePrice, dtype: float64

Manufacturer Summary:
  count      618
unique      70
top       DELL
freq        92
Name: manufacturer, dtype: object

class Summary:
  count         618
unique          3
top       desktop
freq          423
Name: class, dtype: object

Model number Summary:
  count               618
unique              607
top       FX608JHR-ES73
freq                  4
Name: modelNumber, dtype: object

condition Summary:
  count       618
unique        2
top       False
freq        405
Name: isRefurbished, dtype: object

Manufacturer num:
  manufacturer
DELL          92
HP            53
MSI           45
Apple         43
SAMSUNG       40
              ..
Mllse          1
GenMachine     1
suevery        1
MINIHYPER      1
Motorola       1
Name: count, Length: 70, dtype: int64

class num:
  class
desktop    423
laptop     103
phone       92
Name: count, dtype: int64

## Summary Statistics Review

In [ ]:

# Numerical summaries
print("Review Count")
print("Mean Review Count:", df['customerReviewCount'].mean())
print("Median Review Count:", df['customerReviewCount'].median())
print("Mode Review Count:", df['customerReviewCount'].mode()[0])
print("Std of Review Count:",df['customerReviewCount'].std() )
print("Variance of Review Count:",df['customerReviewCount'].var() )
print("Min & Max Review Count:",df['customerReviewCount'].min(), df['customerReviewCount'].max() )

# Using IQR (inter quartile range) method
Q1 = df['customerReviewCount'].quantile(.25)
Q3 = df['customerReviewCount'].quantile(.75)
IQR = Q3 - Q1

lower_fence = Q1 - IQR*1.5
upper_fence = Q3 + IQR*1.5
outliers = df[(df['customerReviewCount']<lower_fence)|(df['customerReviewCount']>upper_fence)]
print("Number of outliers Review Count:", outliers.shape[0])

# Using Z-Score method
from scipy import stats
z = stats.zscore(df['customerReviewCount'])
print("Potential outliers (Z > 3):", df[abs(z) > 3].shape[0])

print("\nReview Rating")
print("Mean Review Rating:", df['customerReviewAverage'].mean())
print("Median Review Rating:", df['customerReviewAverage'].median())
print("Mode Review Rating:", df['customerReviewAverage'].mode()[0])
print("Std of Review Rating:",df['customerReviewAverage'].std() )
print("Variance of Review Rating:",df['customerReviewAverage'].var() )
print("Min & Max Review Rating:",df['customerReviewAverage'].min(), df['customerReviewAverage'].max() )

# Using IQR (inter quartile range) method
Q1 = df['customerReviewAverage'].quantile(.25)
Q3 = df['customerReviewAverage'].quantile(.75)
IQR = Q3 - Q1

lower_fence = Q1 - IQR*1.5
upper_fence = Q3 + IQR*1.5
outliers = df[(df['customerReviewAverage']<lower_fence)|(df['customerReviewAverage']>upper_fence)]
print("Number of outliers Review Rating:", outliers.shape[0])

# Using Z-Score method
z = stats.zscore(df['customerReviewAverage'])
print("Potential outliers (Z > 3):", df[abs(z) > 3].shape[0])

print("\nSale Price")
print("Mean Sale Price:", df['salePrice'].mean())
print("Median Sale Price:", df['salePrice'].median())
print("Mode Sale Price:", df['salePrice'].mode()[0])
print("Std of Sale Price:",df['salePrice'].std() )
print("Variance of Sale Price:",df['salePrice'].var() )
print("Min & Max Sale Price:",df['salePrice'].min(), df['salePrice'].max() )

# Using IQR (inter quartile range) method
Q1 = df['salePrice'].quantile(.25)
Q3 = df['salePrice'].quantile(.75)
IQR = Q3 - Q1

lower_fence = Q1 - IQR*1.5
upper_fence = Q3 + IQR*1.5
outliers = df[(df['salePrice']<lower_fence)|(df['salePrice']>upper_fence)]
print("Number of outliers Sale Price:", outliers.shape[0])

# Using Z-Score method
z = stats.zscore(df['salePrice'])
print("Potential outliers (Z > 3):", df[abs(z) > 3].shape[0])

# Categorical summaries
print('\nManufacturer counts:\n ', df['manufacturer'].value_counts())
print('\nClass Counts:\n ', df['class'].value_counts())

Review Count
Mean Review Count: 7.62725527831094
Median Review Count: 0.0
Mode Review Count: 0    0
Name: customerReviewCount, dtype: int64
Std of Review Count: 47.6414341315624
Variance of Review Count: 2269.706246111999
Min & Max Review Count: 0 892
Number of outliers Review Count: 649
Potential outliers (Z > 3): 31

Review Rating
Mean Review Rating: 1.03573896353167
Median Review Rating: 0.0
Mode Review Rating: 0    0.0
Name: customerReviewAverage, dtype: float64
Std of Review Rating: 1.8814870069529674
Variance of Review Rating: 3.5399933573328357
Min & Max Review Rating: 0.0 5.0
Number of outliers Review Rating: 649
Potential outliers (Z > 3): 0

Sale Price
Mean Sale Price: 728.5568675623799
Median Sale Price: 499.0
Mode Sale Price: 0    299.99
Name: salePrice, dtype: float64
Std of Sale Price: 715.103161366477
Variance of Sale Price: 511372.5313963297
Min & Max Sale Price: 29.0 8100.0
Number of outliers Sale Price: 185
Potential outliers (Z > 3): 42

Manufacturer counts:
  manufacturer
DELL                  399
Apple                 396
HP                    360
SAMSUNG               339
Lenovo                239
MSI                    99
ASUS                   89
Google                 61
Skytech                53
ABS                    45
Acer America           34
Motorola               33
iBUYPOWER              24
STORMCRAFT             23
AVGPC                  20
YEYIAN                 19
Hoengager              18
Cobratype              18
Microsoft              16
Mi                     14
Andromeda Insights     13
CLX                    12
Thermaltake            12
XIDAX                  11
STGAubron               9
IPASON                  9
MXZ                     9
GIGABYTE                7
Higole                  7
Cooler Master           7
CyberpowerPC            7
yeah magic              7
Realme                  6
ACEMAGIC                6
AODU                    6
VERTU                   5
OUKITEL                 5
Intel                   5
Kamrui                  5
OnePlus                 5
Nokia                   5
abytespark              5
Ulefone                 4
Mi-Zone                 4
MLOONG                  4
BLU                     4
Panasonic               4
NINGMEI                 4
AOACE                   4
VTG                     4
SEJISHI                 4
ZOTAC                   4
minisforum              4
MINIHYPER               4
AORUS                   3
Thunderobot             3
ViprTech                3
LG Electronics          3
Periphio                3
Samsung Canada          3
suevery                 3
Bigme                   3
GenMachine              3
Miro Corporation        3
8849                    3
Exsurf                  3
AOC Monitors            2
Corsair                 2
Orbic                   2
KurieTim                2
GAMAKOO                 2
HZG                     2
ArsenalPC               2
Hasee                   2
ZYNEEX                  2
Adamant Custom          2
Allied Gaming           2
ICEWOLF                 2
AQVIN                   1
Kyocera                 1
Redmi                   1
sluting                 1
Mllse                   1
LXZ                     1
ZER-LON                 1
Blackview               1
Sony                    1
Generic Brand           1
Red                     1
LG Mobile               1
Samsung SDS             1
Punkt                   1
Honor                   1
ALCPOK                  1
YAWYORE                 1
Fusion5                 1
TIQ mini Q5             1
DTA Computers           1
Blackout Computers      1
Auusda                  1
Kroteaup                1
N-one                   1
Hyper Cyber             1
YLZKIX                  1
Gateway                 1
NSX GAMING              1
Bitspower               1
NEOSMAY                 1
Velztorm                1
MITXPC                  1
Odyssey Computers       1
Axiom Gaming            1
BiTECOOL                1
Name: count, dtype: int64

Class Counts:
  class
desktop    968
phone      869
laptop     768
Name: count, dtype: int64

In [75]:
#unique value counts and mode detection
print("\nUnique value counts per column:")
print(df.nunique())

Unique value counts per column:
itemNumber               618
class                      3
name                     615
customerReviewAverage     26
customerReviewCount       80
customerTopRated           2
modelNumber              607
salePrice                431
manufacturer              70
isRefurbished              2
dtype: int64

## Exploring Relationships

In [83]:
# Group-based summaries

print("Mean Rating by Class:")
print(df.groupby('class')['customerReviewAverage'].mean())

print("\nMean Rating by Manufacturer:")
print(df.groupby('manufacturer')['customerReviewAverage'].mean())

print("\nMean Review Count by Class:")
print(df.groupby('class')['customerReviewCount'].mean())

print("\nMean Review Count by Manufacturer:")
print(df.groupby('manufacturer')['customerReviewCount'].mean())

print("\nMean Sale Price by Class:")
print(df.groupby('class')['salePrice'].mean())

print("\nMean Sale Price by Manufacturer:")
print(df.groupby('manufacturer')['salePrice'].mean())


# Correlation matrix

df.corr(numeric_only=True)

Mean Rating by Class:
class
desktop    1.936983
laptop     0.552865
phone      0.458573
Name: customerReviewAverage, dtype: float64

Mean Rating by Manufacturer:
manufacturer
8849                  0.666667
ABS                   2.920000
ACEMAGIC              3.216667
ALCPOK                4.900000
AOACE                 4.700000
AOC Monitors          1.850000
AODU                  0.500000
AORUS                 1.333333
AQVIN                 0.000000
ASUS                  1.187640
AVGPC                 4.485000
Acer America          0.585294
Adamant Custom        0.000000
Allied Gaming         0.500000
Andromeda Insights    2.246154
Apple                 0.388889
ArsenalPC             5.000000
Auusda                4.600000
Axiom Gaming          0.000000
BLU                   0.000000
BiTECOOL              5.000000
Bigme                 1.666667
Bitspower             5.000000
Blackout Computers    0.000000
Blackview             0.000000
CLX                   1.383333
Cobratype             3.288889
Cooler Master         2.485714
Corsair               2.500000
CyberpowerPC          0.571429
DELL                  0.967920
DTA Computers         0.000000
Exsurf                0.000000
Fusion5               0.000000
GAMAKOO               0.000000
GIGABYTE              2.800000
Gateway               0.000000
GenMachine            1.666667
Generic Brand         0.000000
Google                0.229508
HP                    0.614167
HZG                   4.700000
Hasee                 0.000000
Higole                2.614286
Hoengager             3.972222
Honor                 0.000000
Hyper Cyber           4.900000
ICEWOLF               0.000000
IPASON                3.255556
Intel                 1.400000
Kamrui                3.000000
Kroteaup              0.000000
KurieTim              2.500000
Kyocera               0.000000
LG Electronics        3.000000
LG Mobile             0.000000
LXZ                   4.600000
Lenovo                0.550209
MINIHYPER             0.750000
MITXPC                0.000000
MLOONG                4.875000
MSI                   2.038384
MXZ                   4.644444
Mi                    0.714286
Mi-Zone               0.000000
Microsoft             0.000000
Miro Corporation      0.000000
Mllse                 4.300000
Motorola              0.303030
N-one                 0.000000
NEOSMAY               0.000000
NINGMEI               4.950000
NSX GAMING            4.000000
Nokia                 0.000000
OUKITEL               0.000000
Odyssey Computers     0.000000
OnePlus               0.000000
Orbic                 0.000000
Panasonic             0.000000
Periphio              3.700000
Punkt                 0.000000
Realme                0.000000
Red                   0.000000
Redmi                 0.000000
SAMSUNG               0.584956
SEJISHI               0.925000
STGAubron             0.555556
STORMCRAFT            4.743478
Samsung Canada        0.000000
Samsung SDS           0.000000
Skytech               2.450943
Sony                  0.000000
TIQ mini Q5           0.000000
Thermaltake           2.291667
Thunderobot           0.000000
Ulefone               1.250000
VERTU                 0.000000
VTG                   2.775000
Velztorm              0.000000
ViprTech              1.466667
XIDAX                 2.009091
YAWYORE               4.800000
YEYIAN                1.768421
YLZKIX                4.900000
ZER-LON               0.000000
ZOTAC                 4.000000
ZYNEEX                5.000000
abytespark            0.800000
iBUYPOWER             3.254167
minisforum            4.200000
sluting               0.000000
suevery               1.666667
yeah magic            1.957143
Name: customerReviewAverage, dtype: float64

Mean Review Count by Class:
class
desktop    19.501033
laptop      0.960938
phone       0.292290
Name: customerReviewCount, dtype: float64

Mean Review Count by Manufacturer:
manufacturer
8849                    0.333333
ABS                    71.977778
ACEMAGIC                1.833333
ALCPOK                263.000000
AOACE                 892.000000
AOC Monitors            4.500000
AODU                    0.333333
AORUS                   0.333333
AQVIN                   0.000000
ASUS                    1.674157
AVGPC                  55.750000
Acer America            3.823529
Adamant Custom          0.000000
Allied Gaming           0.500000
Andromeda Insights      0.769231
Apple                   0.285354
ArsenalPC               2.000000
Auusda                242.000000
Axiom Gaming            0.000000
BLU                     0.000000
BiTECOOL               32.000000
Bigme                   1.333333
Bitspower               1.000000
Blackout Computers      0.000000
Blackview               0.000000
CLX                     0.916667
Cobratype              15.777778
Cooler Master          17.142857
Corsair                 0.500000
CyberpowerPC            4.285714
DELL                    1.107769
DTA Computers           0.000000
Exsurf                  0.000000
Fusion5                 0.000000
GAMAKOO                 0.000000
GIGABYTE                6.571429
Gateway                 0.000000
GenMachine              1.000000
Generic Brand           0.000000
Google                  0.098361
HP                      0.275000
HZG                   101.000000
Hasee                   0.000000
Higole                  3.000000
Hoengager              13.333333
Honor                   0.000000
Hyper Cyber            11.000000
ICEWOLF                 0.000000
IPASON                138.000000
Intel                   0.400000
Kamrui                  1.200000
Kroteaup                0.000000
KurieTim                0.500000
Kyocera                 0.000000
LG Electronics          1.666667
LG Mobile               0.000000
LXZ                   446.000000
Lenovo                  0.393305
MINIHYPER               0.500000
MITXPC                  0.000000
MLOONG                107.000000
MSI                    10.242424
MXZ                    50.000000
Mi                      0.142857
Mi-Zone                 0.000000
Microsoft               0.000000
Miro Corporation        0.000000
Mllse                   6.000000
Motorola                0.060606
N-one                   0.000000
NEOSMAY                 0.000000
NINGMEI               108.500000
NSX GAMING              1.000000
Nokia                   0.000000
OUKITEL                 0.000000
Odyssey Computers       0.000000
OnePlus                 0.000000
Orbic                   0.000000
Panasonic               0.000000
Periphio                2.666667
Punkt                   0.000000
Realme                  0.000000
Red                     0.000000
Redmi                   0.000000
SAMSUNG                 0.374631
SEJISHI                 0.750000
STGAubron               0.111111
STORMCRAFT             51.043478
Samsung Canada          0.000000
Samsung SDS             0.000000
Skytech                 5.037736
Sony                    0.000000
TIQ mini Q5             0.000000
Thermaltake             1.166667
Thunderobot             0.000000
Ulefone                 0.250000
VERTU                   0.000000
VTG                    34.000000
Velztorm                0.000000
ViprTech                6.333333
XIDAX                   2.909091
YAWYORE               442.000000
YEYIAN                108.842105
YLZKIX                 12.000000
ZER-LON                 0.000000
ZOTAC                  64.000000
ZYNEEX                145.500000
abytespark              0.200000
iBUYPOWER              17.416667
minisforum              9.250000
sluting                 0.000000
suevery                 0.333333
yeah magic              2.142857
Name: customerReviewCount, dtype: float64

Mean Sale Price by Class:
class
desktop    977.994473
laptop     743.384922
phone      437.597664
Name: salePrice, dtype: float64

Mean Sale Price by Manufacturer:
manufacturer
8849                   399.660000
ABS                   1576.109778
ACEMAGIC               305.958333
ALCPOK                1291.990000
AOACE                  835.995000
AOC Monitors           489.000000
AODU                  1067.828333
AORUS                 2033.990000
AQVIN                  409.990000
ASUS                  1216.491124
AVGPC                 1269.395000
Acer America           748.595294
Adamant Custom        2899.990000
Allied Gaming          849.990000
Andromeda Insights    2013.836154
Apple                  427.412424
ArsenalPC             2698.000000
Auusda                 439.990000
Axiom Gaming           499.000000
BLU                    143.240000
BiTECOOL               219.000000
Bigme                  244.663333
Bitspower              670.000000
Blackout Computers     499.990000
Blackview              249.990000
CLX                   3225.861667
Cobratype             2016.005000
Cooler Master         2021.081429
Corsair               2060.500000
CyberpowerPC          1707.540000
DELL                   504.581153
DTA Computers          879.990000
Exsurf                 438.323333
Fusion5                139.990000
GAMAKOO                129.590000
GIGABYTE              1941.132857
Gateway                244.990000
GenMachine             272.326667
Generic Brand          599.990000
Google                 414.453443
HP                     565.046444
HZG                    680.000000
Hasee                 1329.990000
Higole                 251.857143
Hoengager             1347.767778
Honor                 1294.980000
Hyper Cyber           5419.000000
ICEWOLF               1184.000000
IPASON                 951.331111
Intel                  480.590000
Kamrui                 193.596000
Kroteaup               349.990000
KurieTim               317.490000
Kyocera                114.990000
LG Electronics         193.876667
LG Mobile              199.970000
LXZ                    396.990000
Lenovo                 668.783724
MINIHYPER              153.990000
MITXPC                 179.990000
MLOONG                1361.500000
MSI                   1543.123333
MXZ                    929.000000
Mi                     380.742857
Mi-Zone                244.990000
Microsoft             1598.680000
Miro Corporation       103.323333
Mllse                  118.000000
Motorola               331.276061
N-one                  288.860000
NEOSMAY                579.000000
NINGMEI               1159.000000
NSX GAMING             699.000000
Nokia                  304.060000
OUKITEL                346.732000
Odyssey Computers      499.990000
OnePlus                447.334000
Orbic                   29.000000
Panasonic              552.997500
Periphio               671.656667
Punkt                  350.000000
Realme                 339.885000
Red                     59.950000
Redmi                  324.990000
SAMSUNG                435.584218
SEJISHI                779.000000
STGAubron              585.267778
STORMCRAFT            1563.685652
Samsung Canada         219.980000
Samsung SDS            879.970000
Skytech               1429.706981
Sony                   343.000000
TIQ mini Q5            140.000000
Thermaltake           1468.200000
Thunderobot           1389.000000
Ulefone                617.490000
VERTU                 4420.000000
VTG                   1674.000000
Velztorm              1799.980000
ViprTech              1018.323333
XIDAX                 2359.080909
YAWYORE                419.990000
YEYIAN                1338.937368
YLZKIX                 659.990000
ZER-LON                439.990000
ZOTAC                 1737.490000
ZYNEEX                 664.495000
abytespark             515.990000
iBUYPOWER             1553.205000
minisforum             419.000000
sluting                339.000000
suevery                499.990000
yeah magic             808.427143
Name: salePrice, dtype: float64

,customerReviewAverage,customerReviewCount,customerTopRated,salePrice,isRefurbished
customerReviewAverage,1.000000,0.294292,0.348527,0.181200,-0.156167
customerReviewCount,0.294292,1.000000,0.474031,0.074173,-0.139007
customerTopRated,0.348527,0.474031,1.000000,0.097690,-0.156750
salePrice,0.181200,0.074173,0.097690,1.000000,-0.426622
isRefurbished,-0.156167,-0.139007,-0.156750,-0.426622,1.000000